export const locations = [
  { text: "Afghanistan", id: "AF" },
  { text: "Albania", id: "AF" },
  { text: "Andorra", id: "DZ" },
  { text: "Albania", id: "AF" },
  { text: "Laos", id: "LA" },
  { text: "Denmark", id: "DK" },
  { text: "Sweden", id: "SE" },
  { text: "Latvia", id: "LV" },
  { text: "Lebanon", id: "LB" },
  { text: "Lesotho", id: "LS" },
  { text: "Angola", id: "AO" },
  { text: "Liberia", id: "LR" },
  { text: "Antigua and Barbuda", id: "AG" },
  { text: "Libya", id: "LY" },
  { text: "Argentina", id: "AR" },
  { text: "Liechtenstein", id: "LI" },
  { text: "Armenia", id: "AM" },
  { text: "Lithuania", id: "LT" },
  { text: "Australia", id: "AU" },
  { text: "Luxembourg", id: "LU" },
  { text: "Austria", id: "AT" },
  { text: "Macedonia", id: "MK" },
  { text: "Azerbaijan", id: "AZ" },
  { text: "Madagascar", id: "MG" },
  { text: "Bahamas", id: "BS" },
  { text: "Malawi", id: "MW" },
  { text: "Bahrain", id: "BH" },
  { text: "Malaysia", id: "MY" },
  { text: "Bangladesh", id: "BD" },
  { text: "Maldives", id: "MV" },
  { text: "Barbados", id: "BB" },
  { text: "Mali", id: "ML" },
  { text: "Belarus", id: "BY" },
  { text: "Malta", id: "MT" },
  { text: "Belgium", id: "BE" },
  { text: "Marshall Islands", id: "MH" },
  { text: "Belize", id: "BZ" },
  { text: "Mauritania", id: "MR" },
  { text: "Benin", id: "BJ" },
  { text: "Mauritius", id: "MU" },
  { text: "Bhutan", id: "BT" },
  { text: "Mexico", id: "MX" },
  { text: "Bolivia", id: "BO" },
  { text: "Micronesia", id: "FM" },
  { text: "Bosnia and Herzegowina", id: "BA" },
  { text: "Moldova", id: "MD" },
  { text: "Botswana", id: "BW" },
  { text: "Monaco", id: "MC" },
  { text: "Brazil", id: "BR" },
  { text: "Mongolia", id: "MN" },
  { text: "Brunei Darussalam", id: "BN" },
  { text: "Morocco", id: "MA" },
  { text: "Bulgaria", id: "BG" },
  { text: "Mozambique", id: "MZ" },
  { text: "Burkina Faso", id: "BF" },
  { text: "yanmar", id: "MM" },
  { text: "Burundi", id: "BI" },
  { text: "Namibia", id: "NA" },
  { text: "Cambodia", id: "KH" },
  { text: "Nauru", id: "NR" },
  { text: "Cameroon", id: "CM" },
  { text: "Nepal", id: "NP" },
  { text: "Canada", id: "CA" },
  { text: "etherlands", id: "NL" },
  { text: "Cape Verde", id: "CV" },
  { text: "New Zealand", id: "NZ" },
  { text: "Central African Republic", id: "CF" },
  { text: "Nicaragua", id: "NI" },
  { text: "Chad", id: "TD" },
  { text: "Niger", id: "NE" },
  { text: "Chile", id: "CL" },
  { text: "Nigeria", id: "NG" },
  { text: "China", id: "CN" },
  { text: "Norway", id: "NO" },
  { text: "Colombia", id: "CO" },
  { text: "Oman", id: "OM" },
  { text: "Comoros", id: "KM" },
  { text: "Pakistan", id: "PK" },
  { text: "Congo, Democratic Republic", id: "CD" },
  { text: "Palau", id: "PW" },
  { text: "Congo, People’s Republic", id: "CG" },
  { text: "Panama", id: "PA" },
  { text: "Costa Rica", id: "CR" },
  { text: "Papua New Guinea", id: "PG" },
  { text: "Cote d'Ivoire", id: "CI" },
  { text: "Paraguay", id: "PY" },
  { text: "Croatia (Local Name: Hrvatska)", id: "HR" },
  { text: "Peru", id: "PE" },
  { text: "Cuba", id: "CU" },
  { text: "Philippines", id: "PH" },
  { text: "Cyprus", id: "CY" },
  { text: "Poland", id: "PL" },
  { text: "Czech Republic", id: "CZ" },
  { text: "Portugal", id: "PT" },
  { text: "Qatar", id: "QA" },
  { text: "Djibouti", id: "DJ" },
  { text: "Puerto Rico", id: "PR" },
  { text: "Dominica", id: "DM" },
  { text: "Romania", id: "RO" },
  { text: "Dominican Republic", id: "DO" },
  { text: "Russian Federation", id: "RU" },
  { text: "East Timor", id: "TL" },
  { text: "Rwanda", id: "RW" },
  { text: "Ecuador", id: "EC" },
  { text: "Saint Kitts and Nevis", id: "KN" },
  { text: "El Salvador", id: "SV" },
  { text: "Saint Lucia", id: "LC" },
  { text: "Equatorial Guinea", id: "GQ" },
  { text: "Saint Vincent and the Grenadines", id: "VC" },
  { text: "Eritrea", id: "ER" },
  { text: "Samoa", id: "WS" },
  { text: "Estonia", id: "EE" },
  { text: "San Marino", id: "SM" },
  { text: "Ethiopia", id: "ET" },
  { text: "Sao Tome and Príncipe", id: "ST" },
  { text: "Fiji", id: "FJ" },
  { text: "Saudi Arabia", id: "SA" },
  { text: "Finland", id: "FI" },
  { text: "Senegal", id: "SN" },
  { text: "France", id: "FR" },
  { text: "Serbia and Montenegro", id: "CS" },
  { text: "Gabon", id: "GA" },
  { text: "Seychelles", id: "SC" },
  { text: "Gambia", id: "GM" },
  { text: "Sierra Leone", id: "SL" },
  { text: "Georgia", id: "GE" },
  { text: "Singapore", id: "SG" },
  { text: "Germany", id: "DE" },
  { text: "Slovakia (Slovak Republic)", id: "SK" },
  { text: "Ghana", id: "GH" },
  { text: "Slovenia", id: "SI" },
  { text: "Greece", id: "GR" },
  { text: "Solomon Islands", id: "SB" },
  { text: "Grenada", id: "GD" },
  { text: "Greenland", id: "GL" },
  { text: "South Africa", id: "ZA" },
  { text: "Guatemala", id: "GT" },
  { text: "Spain", id: "ES" },
  { text: "Guinea", id: "GN" },
  { text: "Sri Lanka", id: "LK" },
  { text: "Guinea-Bissau", id: "GW" },
  { text: "Sudan", id: "SD" },
  { text: "Guyana", id: "GY" },
  { text: "Suriname", id: "SR" },
  { text: "Haiti", id: "HT" },
  { text: "Swaziland", id: "SZ" },
  { text: "Honduras", id: "HN" },
  { text: "Hong Kong", id: "HK" },
  { text: "Switzerland", id: "CH" },
  { text: "Hungary", id: "HU" },
  { text: "Syrian Arab Republic", id: "SY" },
  { text: "Iceland", id: "IS" },
  { text: "Tajikistan", id: "TJ" },
  { text: "India", id: "IN" },
  { text: "Tanzania", id: "TZ" },
  { text: "Indonesia", id: "ID" },
  { text: "Taiwan", id: "TW" },
  { text: "Iran", id: "IR" },
  { text: "Tanzania", id: "TZ" },
  { text: "Iraq", id: "IQ" },
  { text: "Thailand", id: "TH" },
  { text: "Ireland", id: "IE" },
  { text: "Togo", id: "TG" },
  { text: "Israel", id: "IL" },
  { text: "Tonga", id: "TO" },
  { text: "Italy", id: "IT" },
  { text: "Trinidad and Tobago", id: "TT" },
  { text: "Jamaica", id: "JM" },
  { text: "Tunisia", id: "TN" },
  { text: "Japan", id: "JP" },
  { text: "Turkey", id: "TR" },
  { text: "Jordan", id: "JO" },
  { text: "Turkmenistan", id: "TM" },
  { text: "Kazakhstan", id: "KZ" },
  { text: "Tuvalu", id: "TV" },
  { text: "Kenya", id: "KE" },
  { text: "Uganda", id: "UG" },
  { text: "Kiribati", id: "KI" },
  { text: "Ukraine", id: "UA" },
  { text: "Korea, Democratic People's Republic", id: "KP" },
  { text: "United Arab Emirates", id: "AE" },
  { text: "Korea, Republic", id: "KR" },
  { text: "United Kingdom", id: "GB" },
  { text: "Kuwait", id: "KW" },
  { text: "United States", id: "US" },
  { text: "Kyrgyzstan", id: "KG" },
  { text: "Uruguay", id: "UY" }
];
